### ISSUE TITLE
如何自定义API地址？

### ISSUE THREAD

**Issue by lanshao520** [GPTGenius/chatgpt-vercel#15]
今天尝试了几个方法，修改src/pages/api目录里的index文件 没有效果 AI回复还是很慢，甚至有时候还会掉线
![image](https://user-images.githubusercontent.com/68683515/231178027-ab35778c-081c-4f1e-81a7-e409ff0cd902.png)

**Comment by lvqq** [comment]
目前仅支持在本地修改请求地址，线上始终请求 api.openai.com，你是有修改线上请求 host 的需求吗，我可以支持一下

**Comment by lvqq** [comment]
部署的话目前这套可以直接在 vercel 上使用的，你是想部署在自己的服务上么？

**Comment by lanshao520** [comment]
是的  我想部署在我的服务器上

**Comment by lvqq** [comment]
ok，这两个需求近期会支持一下~
- [ ] 支持修改 host
- [ ] 支持自定义部署

**Comment by lanshao520** [comment]
好的  非常感谢

**Comment by lanshao520** [comment]
还建议增加更多的配置项可以灵活使用CHATGPT，例如stop终止符、惩罚等，并且给这些配置加上小小的tips提示，如果允许的话，我更希望可以导出聊天记录和导入聊天记录，感谢
![14550C10](https://user-images.githubusercontent.com/68683515/231194557-f12dc3d8-ca6e-46bd-89e7-cf74de8c07ce.png)

**Comment by lvqq** [comment]
> 还建议增加更多的配置项可以灵活使用CHATGPT，例如stop终止符、惩罚等，并且给这些配置加上小小的tips提示

这个没有问题，非常欢迎提 PR~

> 我更希望可以导出聊天记录和导入聊天记录

导出聊天记录已经支持了，导入这个功能也可以有的

**Comment by lanshao520** [comment]
AI回复中，代码片段 希望可以增加复制按钮

**Comment by lvqq** [comment]
近期会支持

**Comment by lanshao520** [comment]
增加停止Ai回复，有时候问题 AI回答的并不对的时候，需要中断AI回复并调整问题重新提问，如果没有停止AI回复的话 AI输出过长会造成等待

**Comment by lvqq** [comment]
很好的建议~

**Comment by lanshao520** [comment]
预设提示，目前只支持下拉选择，如果预设提示条数过多的话，想要找到自己想要的预设提示比较困难，建议增加搜索和选择框放大

**Comment by lanshao520** [comment]
全局配置的OPENAI API KEY只能配置一个，如果用户没有配置自己的key，都用全局配置的key去访问openai，会触发Openai的并发限制，所以API响应会变慢
建议：openai全局配置的key可以设置多个随机选择去访问openai

**Comment by lvqq** [comment]
> 建议：openai全局配置的key可以设置多个随机选择去访问openai

赞同。可以支持 polling/random 等调度方式

**Comment by lvqq** [comment]
@lanshao520 修改 base url 和停止回复已支持

**Comment by lanshao520** [comment]
构建后如何部署到自己的服务器上面？

**Comment by lvqq** [comment]
这个目前还没有，近期会支持

**Comment by lanshao520** [comment]
好的，优先支持随机调用openaikey这个功能，因为如果用户多了，AI回复基本都在15秒以上

**Comment by lvqq** [comment]
欢迎提 pr~

**Comment by lvqq** [comment]
自定义部署已支持，可参考：[README](https://github.com/GPTGenius/chatgpt-vercel/blob/main/README.zh-CN.md#%E5%85%B6%E4%BB%96%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F)，有问题可另外提其他 issue

**Comment by lanshao520** [comment]
紧急：nodejs版本 18.16.0，pnpm版本7.29.0 编译和本地启动报错 如下图
![image](https://user-images.githubusercontent.com/68683515/232279072-000d49d3-5c52-4936-a460-d9b7df0ca8f1.png)
![image](https://user-images.githubusercontent.com/68683515/232279084-e9029ea3-365f-4864-b9d9-6003a44471a4.png)

**Comment by lanshao520** [comment]
已解决！原因是依赖包里的：@esbuild/linux-x64权限不足

**Comment by lanshao520** [comment]
建议：访客统计、在线访客

**Comment by lvqq** [comment]
> 建议：访客统计、在线访客

通过 Vercel 部署的可以在 vercel 控制面板上看到，自定义部署的可以自行接入相关 sdk 例如 google、百度统计等
