### ISSUE TITLE
发送消息过于频繁会发生错误

### ISSUE THREAD

**Issue by jiayihello** [GPTGenius/chatgpt-vercel#22]
发送消息过于频繁会发生错误，支持多key后会不会解决这个问题呢？
![image](https://user-images.githubusercontent.com/103972455/232214280-746d2a8a-a90c-416f-9581-a139b68bd214.png)

**Comment by lvqq** [comment]
请求频繁限制是 openai 的策略，多 key 配置已经支持了，以逗号分隔，参考 [README](https://github.com/GPTGenius/chatgpt-vercel/blob/main/README.zh-CN.md#%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE)

**Comment by jiayihello** [comment]
更新fork，添加了两个key，重新部署之后显示错误
![image](https://user-images.githubusercontent.com/103972455/232233636-3352a39f-9d2d-41ab-93e1-4b9094ff5b5b.png)

**Comment by jiayihello** [comment]
> 请求频繁限制是 openai 的策略，多 key 配置已经支持了，以逗号分隔，参考 [README](https://github.com/GPTGenius/chatgpt-vercel/blob/main/README.zh-CN.md#%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE)
![image](https://user-images.githubusercontent.com/103972455/232233756-d5ed670a-ae98-42c7-acee-2095c7953926.png)

**Comment by lvqq** [comment]
我这边部署测试了一下这个功能是正常的。可能你的这个 key 是有问题的，我加了一个[错误码展示](https://github.com/GPTGenius/chatgpt-vercel/commit/153e2316549be6b726e79035ba792ac4c58378bf) ，可以对照 openai 官方的错误码对比一下原因

**Comment by jiayihello** [comment]
> 我这边部署测试了一下这个功能是正常的。可能你的这个 key 是有问题的，我加了一个[错误码展示](https://github.com/GPTGenius/chatgpt-vercel/commit/153e2316549be6b726e79035ba792ac4c58378bf) ，可以对照 openai 官方的错误码对比一下原因

新建了两个key，可以了，抱歉由于单个使用我的key是没问题的，没考虑到这方面
