### ISSUE TITLE
回复图片失败

### ISSUE THREAD

**Issue by zrmomo** [GPTGenius/chatgpt-vercel#31]
在提供示例网站中测试生成一张图片 能生成链接 但是无法展示
![image](https://user-images.githubusercontent.com/56543271/233125720-b9ab6524-330a-4ef9-84eb-02e7cf14606b.png)

个人部署的网站测试无法生成图片
![image](https://user-images.githubusercontent.com/56543271/233125993-45d66421-fd18-4bc4-8d42-99aa5d8bcc47.png)

**Comment by lvqq** [comment]
文本对话中的图片链接不一定有效，生成图片是单独的会话，入口在这里：

![image](https://user-images.githubusercontent.com/29809148/233127790-c5fa4848-c867-4d7d-be50-e68a6e1062be.png)

**Comment by zrmomo** [comment]
> 

感谢回复
