### ISSUE TITLE
丢失回复

### ISSUE THREAD

**Issue by zrmomo** [GPTGenius/chatgpt-vercel#34]
点击回复的网址，跳转到对应页面，然后返回会丢失回复的最后一条信息。
本来有两个回复，两次跳转返回后都丢失了。
![image](https://user-images.githubusercontent.com/56543271/233242957-0e628b4c-14d1-4340-9eed-903e3cc2ba37.png)

**Comment by lvqq** [comment]
有更详细的操作步骤吗？我这里没有办法复现呢，例如是否在信息未回复完时点击了链接？

**Comment by zrmomo** [comment]
> 有更详细的操作步骤吗？我这里没有办法复现呢，例如是否在信息未回复完时点击了链接？
抱歉 我这里不能稳定复现了 可能是偶现的情况

**Comment by zrmomo** [comment]
抱歉 我这里不能稳定复现了 可能是偶现的情况
