### ISSUE TITLE
作者我能联系你吗

### ISSUE THREAD

**Issue by lanshao520** [GPTGenius/chatgpt-vercel#35]
我想跟你在
chatgpt-vercel基础上定制一款AI绘画（按量付费），GPT3.5和dall-e是开放使用的，定制调用百度ERNIE-ViLG模型，openai的dall-e绘画能力实在太差了

**Comment by lvqq** [comment]
twitter 或者掘金私信我吧

**Comment by lanshao520** [comment]
你的掘金链接是多少

**Comment by lvqq** [comment]
https://juejin.cn/user/1433418893637454
