### ISSUE TITLE
key部署网站点就被删除

### ISSUE THREAD

**Issue by Epiphany7725** [GPTGenius/chatgpt-vercel#37]
key在部署网站后就被删除，有什么解决办法

**Comment by lvqq** [comment]
可以详细描述一下吗？具体哪里的 key，在哪里部署后被删除

**Comment by Epiphany7725** [comment]
是open ai提供的key，只要在.env中配置了key，网站部署成功后就会被open ai删除，导致无法使用

**Comment by lvqq** [comment]
你是通过 vercel 部署的？我这边没有遇到过这个问题呢

**Comment by Epiphany7725** [comment]
是通过vercel部署的

**Comment by lvqq** [comment]
目前不太清楚是 vercel 部署机房的问题还是你的账号的问题呢，这边已经[配置]((https://github.com/GPTGenius/chatgpt-vercel/blob/main/src/pages/api/index.ts#L35~L56))过了的
