### ISSUE TITLE
关于画图选择模型

### ISSUE THREAD

**Issue by Greysonzs** [GPTGenius/chatgpt-vercel#47]
生成MIDjourney图片 需要在模型中选择midjourney模型吗 还是选择dall e模型过后在输入框前面加入mdjrny-v4 style就可以了

**Comment by lvqq** [comment]
目前线上 Midjourney 模型不可用，可以选择 DALL•E 模型

**Comment by Greysonzs** [comment]
是在本地配置频道token吗 在哪里配置呢

**Comment by lvqq** [comment]
目前不需要配置 Token，直接选择Midjourney 即可，有一定免费额度

**Comment by leongxj123** [comment]
直接选择MJ模型会报：Unexpected token '<', "<h"... is not valid JSON

**Comment by lvqq** [comment]
#50 中已经正式支持了 midjourney，需要设置 discord 相关的字段来使用
