### ISSUE TITLE
[feat] 能否加多一个功能，支持放大对话输入框，方便多行输入

### ISSUE THREAD

**Issue by wanghsinche** [GPTGenius/chatgpt-vercel#49]
chatgpt 对格式化数据更敏感，能否在发送按钮旁边加多一个按钮，点击之后输入框变大，enter键不再默认发送，而是换行。这样子用户可以方便的对prompt进行编辑。

**Comment by lvqq** [comment]
可以考虑新增设置，选择 `Enter` 或者 `Shift` + `Enter` 发送
