### ISSUE TITLE
支持页面内语言选择、语音输入输出和对话导出功能

### ISSUE THREAD

**Issue by erbanku** [GPTGenius/chatgpt-vercel#5]
尊敬的维护者和贡献者，

您好！首先，我要感谢您在这个项目上所做的出色工作。在此，我有一些建议，我相信这些功能可以大大提高用户体验。

希望支持：
- 页面内语言选择功能：希望能够在网页上直接切换不同的语言选项，让用户可以更方便地选择他们想要的语言。

- 语音输入输出功能：我发现 `chatkit.app` 在这方面做得非常好，它使用了Azure TTS。如果我们能在项目中加入类似的语音输入和输出功能，将会使用户体验更加丰富。

- 对话Markdown导出功能：希望能提供一个简单的方法，让用户能够将他们的对话导出为Markdown文件，以便他们可以在其他地方使用或存储这些信息。

再次感谢您为这个项目所付出的努力，期待您的回复。祝好！

> 注：该issue由ChatGPT生成

**Comment by lvqq** [comment]
感谢由 ChatGPT 生成的建议 😂，这些都在后续的支持计划内，后续会支持

**Comment by lvqq** [comment]
语言切换在 #8 中支持了

**Comment by FatDoge** [comment]
对话导出已经支持
