### ISSUE TITLE
discord images

### ISSUE THREAD

**Issue by rossman22590** [GPTGenius/chatgpt-vercel#51]
so it works on my dicsord but is NOT displayed.

Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()
/api/images?model=Midjourney&prompt=a%20car&serverId=&channelId=&token=:1     Failed to load resource: the server responded with a status of 400 ()

**Comment by lvqq** [comment]
Could u help to check what message the 400 interface returns?

**Comment by lvqq** [comment]
> 我也遇到web不能返回图片，但是discord里面是有消息的，是不是因为session_id 的问题？

是指成功触发了 discord 但是没有接收到返回图片？方便看一下查询接口返回了什么吗

**Comment by CaoYunzhou** [comment]
跟上面老外贴的日志差不多，看起来就是前端没拿到，网页显示504

**Comment by lvqq** [comment]
It should be fixed in #53, feel free to reopen it if it still happens.
