### ISSUE TITLE
Midjourney生成的图片支持放大 微调

### ISSUE THREAD

**Issue by dxcbl008** [GPTGenius/chatgpt-vercel#57]
用Midjourney生成的图片是否可以支持后续的操作呢
目前已经有这样的例子了
![](https://camo.githubusercontent.com/ec5bce5e161a04c062c2e328a6f62f7d81eb929b27000951f21c00c2c74ddb16/68747470733a2f2f73332e626d702e6f76682f696d67732f323032332f30352f31352f663063376636376566336562303735622e706e67)

**Comment by dxcbl008** [comment]
> 在开发计划中，近期会支持

midjourney的账号池 是否在计划中呢 一个账号的线程有限 多人使用的话 超过线程会报错

**Comment by ItManner** [comment]
后台正在开发，已支持多账号配置
