### ISSUE TITLE
Error: Interactions failed with 400

### ISSUE THREAD

**Issue by adminlove520** [GPTGenius/chatgpt-vercel#62]
![image](https://github.com/GPTGenius/chatgpt-vercel/assets/32920883/42b1bc7f-5463-4540-abbd-1f1d76737455)
这个报错是啥情况呀  mj的参数也配好了的

**Comment by lvqq** [comment]
检查下配置是否有误以及 token 是否过期呢

**Comment by lvqq** [comment]
我在 [57334e](https://github.com/GPTGenius/chatgpt-vercel/commit/57334e4333a1309ba27e9ae3c13486c4ad484c95) 中修复了来自 discord 的错误信息未展示的问题，现在配置填写错误时会得到以下回复：

![image](https://github.com/GPTGenius/chatgpt-vercel/assets/29809148/2d5a8fd2-423c-4c9f-bcf1-788d491a7b62)
