### ISSUE TITLE
国内使用vercel部署后（已设置域名中转），midjourney图像仍无法加载

### ISSUE THREAD

**Issue by l1uchao** [GPTGenius/chatgpt-vercel#66]
如题，国内使用vercel部署成功后，并已成功设置国内可直接访问的域名，域名能在国内不翻墙直接打开。但使用midjourney功能生成图像后，如果不翻墙，就无法正确加载图像。翻墙后，才能正确加载。

猜测原因是，生成的图像仍然是discord域名下的图像markdown图像，国内无法直接访问，所以一直无法加载。翻墙后，才能正确显示。

**Comment by l1uchao** [comment]
是否能增加图像路径转换的过程，就是把discord域名下的markdown图像，转成国内能直接访问的域名下的markdown图像

**Comment by lvqq** [comment]
可以支持配置代理域名批量替换返回的接口 url，代理服务需要自行搭建

**Comment by yigeimuya** [comment]
> 

请问域名已经做好代理服务了，要在哪里批量替换返回的图片的域名URL呢

**Comment by lvqq** [comment]
参考 readme，设置 DISCORD_IMAGE_PROXY

**Comment by 0smboy** [comment]
如何部署Discord image proxy？可以直接在vercel上配置域名转发吗？
