### ISSUE TITLE
默认回车发送对话容易误操作

### ISSUE THREAD

**Issue by fimreal** [GPTGenius/chatgpt-vercel#67]
用的 macos 自带的中文输入法，想按回车直接键入英文的话，这时候会直接触发对话请求，不清楚其他输入法是否有相同问题。

了解下代码哪部分可以修改默认换行快捷键也行。个人习惯用更容易的 enter 进行换行这种频繁操作，复杂点的 command + enter 来发送会话（确认）。

自己尝试着改了几次都没有生效，故来请教下作者大大。

**Comment by lvqq** [comment]
https://github.com/GPTGenius/chatgpt-vercel/blob/main/src/modules/Content/MessageInput.tsx#L96

**Comment by lvqq** [comment]
Refer: https://github.com/GPTGenius/chatgpt-vercel/issues/49
