### ISSUE TITLE
手机浏览器返回不是上一层

### ISSUE THREAD

**Issue by Funyu78** [GPTGenius/chatgpt-vercel#78]
每次返回一下就退出了，能改一下吗，逻辑麻烦就算了，我用HBuilderX打包成app返回退出就很奇怪

**Comment by lvqq** [comment]
整个站点只有一个路由，所以返回就退出到前一个网页了。可以加一下

**Comment by Funyu78** [comment]
> 整个站点只有一个路由，所以返回就退出到前一个网页了。可以优化一下移动端的返回

感谢回复，明白了
