### ISSUE TITLE
很重要，token限制和首页message支持html标签

### ISSUE THREAD

**Issue by lanshao520** [GPTGenius/chatgpt-vercel#9]
不要一味的把用户聊天记录一股脑的传过去，这样做不明智，判断token超过一定数量的时候把前面的聊天记录清空一部分再调用API更合理，不然如果长文本的话没问几句就要清空一次聊天记录，首页应该做一些html标签的支持或者markdown写法

**Comment by lvqq** [comment]
感谢建议~
- markdown 是已经支持的
- token 的问题可以增加一个配置，默认发送最近 x 条消息
